name: olmo7-ablation  # can't have "_" or "." here
image: mosaicml/pytorch:2.1.2_cu121-python3.10-ubuntu20.04
compute:
  gpu_num: 64
  cluster: r12z3
  gpu_type: a100_40gb
integrations:
  - integration_type: git_repo
    git_repo: allenai/LLM
    git_branch: olmo7-ablations
    #git_commit: d765e8819f5b0be204c96b0b519de2372b0da729
    pip_install: -e .
    ssh_clone: true
command: |-
  pip freeze
  mkdir -p /root/.cache/torch/

  export OMP_NUM_THREADS=8
  export LOG_FILTER_TYPE=local_rank0_only
  #export OLMO_NO_SSL=1

  cd LLM
  
  torchrun \
  --master_addr $MASTER_ADDR \
  --master_port $MASTER_PORT \
  --nnodes $NUM_NODES \
  --node_rank $NODE_RANK \
  --nproc_per_node 8 \
  scripts/train.py configs/olmo7b-ablation.yaml \
    --run_name=olmo7-ablation-baseline \
    --wandb.name=baseline \
    --compile.fullgraph=false \
    --model.flash_attention=true \
    --save_folder=runs/ \
    --device_train_microbatch_size=2
