run_name: bff-tiny-deduped-run-001
seed: 6198
dry_run: false

wandb:
  name: ${run_name}
  log_interval: ${console_log_interval}

model:
  d_model: 1024
  n_heads: 16
  n_layers: 16
  mlp_ratio: 8
  alibi: true
  alibi_bias_max: 8.0
  flash_attention: false
  attention_dropout: 0.0
  attention_layer_norm: false
  multi_query_attention: true
  block_type: sequential
  layer_norm_type: low_precision  # if not compiling, use 'low_precision'
  activation_type: swiglu
  residual_dropout: 0.0
  embedding_dropout: 0.0
  max_sequence_length: 1024
  include_bias: true
  vocab_size: 50280
  embedding_size: 50304
  eos_token_id: 0
  pad_token_id: 0
  init_device: meta
  init_std: 0.02

#compile: null  # causes instability on AMD GPUs
compile:
  mode: default

optimizer:
  name: adamw
  learning_rate: 2.0e-3
  weight_decay: 0.1
  betas:
    - 0.9
    - 0.95

scheduler:
  name: cosine_with_warmup
  t_warmup: 2000
  alpha_f: 0.1

data:
  paths:
    - s3://ai2-dirkg/2022-05/c5-deduped-2022-05.npy/00000_00000.npy
    - s3://ai2-dirkg/2022-05/c5-deduped-2022-05.npy/00001_00000.npy
    - s3://ai2-dirkg/2022-05/c5-deduped-2022-05.npy/00002_00000.npy
    - s3://ai2-dirkg/2022-05/c5-deduped-2022-05.npy/00003_00000.npy
    - s3://ai2-dirkg/2022-05/c5-deduped-2022-05.npy/00004_00000.npy
    - s3://ai2-dirkg/2022-05/c5-deduped-2022-05.npy/00005_00000.npy
    - s3://ai2-dirkg/2022-05/c5-deduped-2022-05.npy/00006_00000.npy
    - s3://ai2-dirkg/2022-05/c5-deduped-2022-05.npy/00007_00000.npy
    - s3://ai2-dirkg/2022-05/c5-deduped-2022-05.npy/00008_00000.npy
    - s3://ai2-dirkg/2022-05/c5-deduped-2022-05.npy/00009_00000.npy
    - s3://ai2-dirkg/2022-05/c5-deduped-2022-05.npy/00010_00000.npy
    - s3://ai2-dirkg/2022-05/c5-deduped-2022-05.npy/00011_00000.npy
    - s3://ai2-dirkg/2022-05/c5-deduped-2022-05.npy/00012_00000.npy
    - s3://ai2-dirkg/2022-05/c5-deduped-2022-05.npy/00013_00000.npy
    - s3://ai2-dirkg/2022-05/c5-deduped-2022-05.npy/00014_00000.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00000_00000.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00000_00001.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00001_00000.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00001_00001.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00002_00000.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00002_00001.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00003_00000.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00003_00001.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00004_00000.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00004_00001.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00005_00000.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00005_00001.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00006_00000.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00006_00001.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00007_00000.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00007_00001.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00008_00000.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00008_00001.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00009_00000.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00009_00001.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00010_00000.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00010_00001.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00011_00000.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00011_00001.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00012_00000.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00012_00001.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00013_00000.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00013_00001.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00014_00000.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00014_00001.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00015_00000.npy
    - s3://ai2-dirkg/2022-21/c5-deduped-2022-21.npy/00015_00001.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00000_00000.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00000_00001.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00001_00000.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00001_00001.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00002_00000.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00002_00001.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00003_00000.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00003_00001.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00004_00000.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00004_00001.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00005_00000.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00005_00001.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00006_00000.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00006_00001.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00007_00000.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00007_00001.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00008_00000.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00008_00001.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00009_00000.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00009_00001.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00010_00000.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00010_00001.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00011_00000.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00011_00001.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00012_00000.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00012_00001.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00013_00000.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00013_00001.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00014_00000.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00014_00001.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00015_00000.npy
    - s3://ai2-dirkg/2022-27/c5-deduped-2022-27.npy/00015_00001.npy
  pad_direction: right
  num_workers: 64
  drop_last: true
  pin_memory: true
  prefetch_factor: 4  # bump to 16 if on LUMI
  persistent_workers: true
  timeout: 0

tokenizer:
  identifier: allenai/eleuther-ai-gpt-neox-20b-pii-special
  truncate_direction: right

save_folder: ${oc.env:SCRATCH_DIR,/data/dirkg}/bff-tiny-deduped/
save_overwrite: false
# Sharded checkpoints (best for restarts)
save_interval: 2000
save_num_checkpoints_to_keep: 2
# Unsharded checkpoints (for final storage)
save_interval_unsharded: 200000
save_num_unsharded_checkpoints_to_keep: -1

load_path: null

max_duration: 953674  # 500B tokens
global_train_batch_size: 512
device_train_microbatch_size: 32
time_limit: null

precision: amp_bf16

max_grad_norm: 1.0

speed_monitor:
  window_size: 20

console_log_interval: 20

eval_interval: ${save_interval}
eval_subset_num_batches: -1
device_eval_batch_size: ${device_train_microbatch_size}
evaluators:
  ##########################
  # Perplexity evaluations #
  ##########################
  - label: c4-validation
    subset_num_batches: 10
    data:
      paths: ${path.glob:${path.choose:${oc.env:SCRATCH_DIR,no_exist}/pretraining_data/preprocessed,/net/nfs.cirrascale/allennlp/llm-data}/c4/en/c4-validation.*.npy}
      num_workers: 2
      drop_last: true
      pin_memory: true
      persistent_workers: true
      prefetch_factor: 4

  - label: rp-validation
    subset_num_batches: 10
    data:
      paths: ${path.glob:${path.choose:${oc.env:SCRATCH_DIR,no_exist}/pretraining_data/preprocessed,/net/nfs.cirrascale/allennlp/llm-data}/redpajama/redpajama-validation.npy}
      num_workers: 2
      drop_last: true
      pin_memory: true
      persistent_workers: true
      prefetch_factor: 4

  # lump all the small datasets together (we still get separate metrics).
  - label: all-small-ppl-validation
    data:
      datasets:
        4chan-validation:
          - ${path.choose:${oc.env:SCRATCH_DIR,no_exist},/net/nfs.cirrascale/allennlp/llm-data}/eval-data/perplexity/v2_small_gptneox20b/4chan/val.npy
        c4_100_domains-validation:
          - ${path.choose:${oc.env:SCRATCH_DIR,no_exist},/net/nfs.cirrascale/allennlp/llm-data}/eval-data/perplexity/v2_small_gptneox20b/c4_100_domains/val.npy
        c4_en-validation:
          - ${path.choose:${oc.env:SCRATCH_DIR,no_exist},/net/nfs.cirrascale/allennlp/llm-data}/eval-data/perplexity/v2_small_gptneox20b/c4_en/val.npy
        gab-validation:
          - ${path.choose:${oc.env:SCRATCH_DIR,no_exist},/net/nfs.cirrascale/allennlp/llm-data}/eval-data/perplexity/v2_small_gptneox20b/gab/val.npy
        ice-validation:
          - ${path.choose:${oc.env:SCRATCH_DIR,no_exist},/net/nfs.cirrascale/allennlp/llm-data}/eval-data/perplexity/v2_small_gptneox20b/ice/val.npy
        m2d2_s2orc-validation:
          - ${path.choose:${oc.env:SCRATCH_DIR,no_exist},/net/nfs.cirrascale/allennlp/llm-data}/eval-data/perplexity/v2_small_gptneox20b/m2d2_s2orc/val.npy
        m2d2_wiki-validation:
          - ${path.choose:${oc.env:SCRATCH_DIR,no_exist},/net/nfs.cirrascale/allennlp/llm-data}/eval-data/perplexity/v2_small_gptneox20b/m2d2_wiki/val.npy
        manosphere-validation:
          - ${path.choose:${oc.env:SCRATCH_DIR,no_exist},/net/nfs.cirrascale/allennlp/llm-data}/eval-data/perplexity/v2_small_gptneox20b/manosphere/val.npy
        mc4_en-validation:
          - ${path.choose:${oc.env:SCRATCH_DIR,no_exist},/net/nfs.cirrascale/allennlp/llm-data}/eval-data/perplexity/v2_small_gptneox20b/mc4_en/val.npy
        pile-validation:
          - ${path.choose:${oc.env:SCRATCH_DIR,no_exist},/net/nfs.cirrascale/allennlp/llm-data}/eval-data/perplexity/v2_small_gptneox20b/pile/val.npy
        ptb-validation:
          - ${path.choose:${oc.env:SCRATCH_DIR,no_exist},/net/nfs.cirrascale/allennlp/llm-data}/eval-data/perplexity/v2_small_gptneox20b/ptb/val.npy
        twitterAEE-validation:
          - ${path.choose:${oc.env:SCRATCH_DIR,no_exist},/net/nfs.cirrascale/allennlp/llm-data}/eval-data/perplexity/v2_small_gptneox20b/twitterAEE/val.npy
        wikitext_103-validation:
          - ${path.choose:${oc.env:SCRATCH_DIR,no_exist},/net/nfs.cirrascale/allennlp/llm-data}/eval-data/perplexity/v2_small_gptneox20b/wikitext_103/val.npy
      drop_last: true

  ##########################
  # Downstream evaluations #
  ##########################
  - label: piqa
    type: downstream

  - label: hellaswag
    type: downstream

  - label: winogrande
    type: downstream

  - label: openbook_qa
    type: downstream

  # - label: boolq  # requires implementation of the pmi_dc matrix
    # type: downstream
    #
  - label: sciq
    type: downstream

  - label: arc_easy
    type: downstream

  # - label: arc_challenge  # requires implementation of the pmi_dc matrix
    # type: downstream
    #
  - label: copa
    type: downstream

  - label: rte
    type: downstream

  - label: commitment_bank
    type: downstream

  - label: mrpc
    type: downstream

  - label: sst2
    type: downstream
